# Generated by Django 3.2.6 on 2023-03-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_used',
            new_name='is_expired',
        ),
    ]
