# Generated by Django 3.2.6 on 2023-03-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
    ]
