# Generated by Django 3.2.6 on 2023-03-22 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_coupon_transferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='transferred',
        ),
    ]
