# Generated by Django 3.2.6 on 2023-03-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_cartitems_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='product',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
