# Generated by Django 3.2.6 on 2023-03-14 10:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=1, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='bonushistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonusesamount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_bonuses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
