# Generated by Django 3.2.6 on 2023-03-14 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_bonushistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonushistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
