# Generated by Django 3.2.6 on 2023-03-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='AboutMe',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
