# Generated by Django 3.2.6 on 2023-03-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='AboutMe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
